//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoSharing.Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.UploadPhotosSoap")]
    public interface UploadPhotosSoap {
        
        // CODEGEN: Generating message contract since element name imageBase64 from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Upload", ReplyAction="*")]
        PhotoSharing.Tests.ServiceReference1.UploadResponse Upload(PhotoSharing.Tests.ServiceReference1.UploadRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Upload", Namespace="http://tempuri.org/", Order=0)]
        public PhotoSharing.Tests.ServiceReference1.UploadRequestBody Body;
        
        public UploadRequest() {
        }
        
        public UploadRequest(PhotoSharing.Tests.ServiceReference1.UploadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string imageBase64;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string photoId;
        
        public UploadRequestBody() {
        }
        
        public UploadRequestBody(string imageBase64, string photoId) {
            this.imageBase64 = imageBase64;
            this.photoId = photoId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UploadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UploadResponse", Namespace="http://tempuri.org/", Order=0)]
        public PhotoSharing.Tests.ServiceReference1.UploadResponseBody Body;
        
        public UploadResponse() {
        }
        
        public UploadResponse(PhotoSharing.Tests.ServiceReference1.UploadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UploadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UploadResult;
        
        public UploadResponseBody() {
        }
        
        public UploadResponseBody(bool UploadResult) {
            this.UploadResult = UploadResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UploadPhotosSoapChannel : PhotoSharing.Tests.ServiceReference1.UploadPhotosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UploadPhotosSoapClient : System.ServiceModel.ClientBase<PhotoSharing.Tests.ServiceReference1.UploadPhotosSoap>, PhotoSharing.Tests.ServiceReference1.UploadPhotosSoap {
        
        public UploadPhotosSoapClient() {
        }
        
        public UploadPhotosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UploadPhotosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadPhotosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UploadPhotosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PhotoSharing.Tests.ServiceReference1.UploadResponse PhotoSharing.Tests.ServiceReference1.UploadPhotosSoap.Upload(PhotoSharing.Tests.ServiceReference1.UploadRequest request) {
            return base.Channel.Upload(request);
        }
        
        public bool Upload(string imageBase64, string photoId) {
            PhotoSharing.Tests.ServiceReference1.UploadRequest inValue = new PhotoSharing.Tests.ServiceReference1.UploadRequest();
            inValue.Body = new PhotoSharing.Tests.ServiceReference1.UploadRequestBody();
            inValue.Body.imageBase64 = imageBase64;
            inValue.Body.photoId = photoId;
            PhotoSharing.Tests.ServiceReference1.UploadResponse retVal = ((PhotoSharing.Tests.ServiceReference1.UploadPhotosSoap)(this)).Upload(inValue);
            return retVal.Body.UploadResult;
        }
    }
}
